### ISSUE TITLE
get response without fill visa information

### ISSUE THREAD

**Issue by krinkel** [recca0120/laravel-payum#5]
i used payum, it has a bug with payex, but when use your package it work successfully :) grate work, thank you.
my problem now when i visit prepare page:
http://project.dev:8000/en/payment/payex
it is redirect me directly to:
http://project.dev:8000/en/payment/done/6ZSqW2986XZZGKlvuImyuA2QV38MsQlj9Br6wjGCK4A
without fill any visa information, so the response get failed!!
the first and second time i test the payment it redirect me to fill visa and the payment successfully done, but now after tow or three times i can’t test more, it same that the service cached my request and get failed response, i don’t know why .. but is it can be fix?

**Comment by recca0120** [comment]
I guess..
1. 
do you set same number when you use $payum->setNumber()?
setNumber must be unique

2.
you could find file name like %6ZSqW2986XZZGKlvuImyuA2QV38MsQlj9Br6wjGCK4A% at path storage/payum, and check it

3.
try clean folder stroage/payum

**Comment by krinkel** [comment]
thanks a lot for help,
but i tried to change the number & clean storage/payum folder, but still get failed.
i check the storage/payum folder after failed response and found two files called (payum-model-8547586325) and (payum-model-KlYVvpqADSJgHTnyKZuN0lZJIYXarTw8AyxBAO8XlL0) contains a lot of numbers like: 4f3a 3232 3a22 5061 ....etc

it may be useful to know that i use (payex) gateway
the response contain the error reason but i still can’t understand the problem reason
```
[errorCode] => ValidationError_HashNotValid
[errorDescription] => Admin.ValidateMerchantLogon:Invalid hash
```

and that is the full response:

```
stdClass Object
(
    [status] => failed
    [client] => stdClass Object
        (
            [id] => 2
            [email] => user@domain.com
        )
    [number] => 8547586325
    [description] => SEK
    [total_amount] => 15.5
    [currency_code] => SEK
    [details] => stdClass Object
        (
            [price] => 15.5
            [priceArgList] => 
            [vat] => 0
            [currency] => SEK
            [orderId] => 8547586325
            [productNumber] => n\a
            [purchaseOperation] => SALE
            [view] => CREDITCARD
            [description] => 
            [clientIdentifier] => 
            [additionalValues] => 
            [agreementRef] => 
            [clientLanguage] => en-US
            [autoPay] => 
            [returnUrl] => http://myproject.dev:8000/payment/capture/BFJ3dwReyZ2f9bsj9jlfm0Z9tiJwGVA8p97hApsu-P8
            [cancelUrl] => http://myproject.dev:8000/payment/capture/BFJ3dwReyZ2f9bsj9jlfm0Z9tiJwGVA8p97hApsu-P8
            [clientIPAddress] => 10.0.2.2
            [errorCode] => ValidationError_HashNotValid
            [errorDescription] => Admin.ValidateMerchantLogon:Invalid hash
            [paramName] => Array
                (
                )
            [thirdPartyError] => Array
                (
                )
        )
)
```

and when trying to use paypal_express_checkout gateway, i change the number again as you till but i got this failed response without ask for PayPal account or any data:

```
stdClass Object
(
    [status] => failed
    [client] => stdClass Object
        (
            [id] => 2
            [email] => user@domain.com
        )
    [number] => 854758632558
    [description] => SEK
    [total_amount] => 15.5
    [currency_code] => SEK
    [details] => stdClass Object
        (
            [INVNUM] => 854758632558
            [PAYMENTREQUEST_0_CURRENCYCODE] => SEK
            [PAYMENTREQUEST_0_AMT] => 0.155
            [PAYMENTREQUEST_0_DESC] => 
            [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
            [AUTHORIZE_TOKEN_USERACTION] => commit
            [RETURNURL] => http://myproject.dev:8000/payment/capture/09HP0RnQgU_5Z-wGqHj2PxFo4VwaiHA1ZrsIb4Qds-k
            [CANCELURL] => http://myproject.dev:8000/payment/capture/09HP0RnQgU_5Z-wGqHj2PxFo4VwaiHA1ZrsIb4Qds-k?cancelled=1
            [PAYMENTREQUEST_0_NOTIFYURL] => http://myproject.dev:8000/payment/notify/M2FqcpR8NBD3X5l-1YamqJ5EDMxklYYINcvbbqnLi9o
            [TIMESTAMP] => 2016-08-25T22:05:31Z
            [CORRELATIONID] => 60d84d25ba5c3
            [ACK] => Failure
            [VERSION] => 65.1
            [BUILD] => 24764620
            [L_ERRORCODE0] => 10002
            [L_SHORTMESSAGE0] => Security error
            [L_LONGMESSAGE0] => Security header is not valid
            [L_SEVERITYCODE0] => Error
        )
)
```
it is the same problem, i get response error directly after redirect, without fill any information.
any idea? @recca0120

**Comment by recca0120** [comment]
is it the same problem when you use only payum??

if it's work...
this problem will be in this this package

if not
maybe payex api is changed or other problem....

**Comment by recca0120** [comment]
Hi @krinkel 
I found in payex offical website can download [sample code](http://www.payexpim.com/downloads/example-code/)

you could download it and test you account is correct??

if everything is fine, maybe payex change the api...

so... you need to implements payex by yourself

and there is another offical [sdk](https://github.com/PayEx/PayEx.Ecommerce.Php), you can try too

It's hard to test payex, because I don't have any account in payex..

if you could offer me a test account...

maybe I can do some test....
