### ISSUE TITLE
This package not working with Payex at all 

### ISSUE THREAD

**Issue by mahmouddev** [recca0120/laravel-payum#6]
I tested this package an try to use it for Payex payment but not working 
I have failed response 

`[status] => failed`

this is my configration 

*****************************************************************************************
    return [
        'route' => [
            'prefix'     => 'payment',
            'as'         => 'payment.',
            'middleware' => 'web',
        ],
        'storage' => [
            // optioins: eloquent, filesystem
            'token'         => 'filesystem',
            // optioins: eloquent, filesystem
            'gatewayConfig' => 'filesystem',
        ],
        'gatewayConfigs' => [
            'payex' => [
                'factory'        => Payum\Payex\PayexGatewayFactory::class,
                'account_number' => 'xxxxxxxx',
                'encryption_key' => 'xxxxxxxxxxxxxxxx',
                'sandbox'        => true
            ],
        ],
    ];
*****************************************************************************************

but i have error 

****
            [errorCode] => ValidationError_HashNotValid
            [errorDescription] => Admin.ValidateMerchantLogon:Invalid hash
***

i think it is the same isuee for @krinkel #5 

plese help @recca0120

**Comment by makasim** [comment]
I've just tested the payex scenarios in the [sandbox](https://github.com/makasim/PayumBundleSandbox).

1. Simple purchase
2. Store a credit card reference and use later
3. Recurring payments

All works just fine.

1. So please make sure you set correct payex credentials and other configurations are correct.
2. Make sure you are using payex sandbox environment and use credit cards from here http://www.payexpim.com/test-data/test-purchase-data/
